### ISSUE TITLE
How to configure the site 

### ISSUE THREAD

**Issue by gopakumar** [mattbutton/silhouette-hugo#10]
Hello,

First all thank you very much for the beautiful theme. I am new to HTML, I am looking for a doc to configure the theme, example site dosent contain anything

Thank you

**Comment by gopakumar** [comment]
never mind I figured it out

**Comment by mattbutton** [comment]
For anybody else who sees this, the commands will look like:

`cp themes/silhouette-hugo/exampleSite/* . -r`

Then:

`hugo serve -D`
