### ISSUE TITLE
Site not rendering correctly on recent hugo version

### ISSUE THREAD

**Issue by condwanaland** [mattbutton/silhouette-hugo#11]
I just tried downloading your site theme and deploying it locally. When serving locally, some of the styling seems to be off (text misplaced, recent posts no longer in sidebar)

<img width="1439" alt="Screen Shot 2021-01-14 at 7 55 34 PM" src="https://user-images.githubusercontent.com/23396385/104555422-b49fe300-56a2-11eb-8287-e0619be22240.png">

This is with Hugo version ‘0.75.1’

**Comment by condwanaland** [comment]
This was user error, and related to R versions, not hugo versions. Closing

**Comment by mattbutton** [comment]
Thanks Conor, glad you got it figured out.
