### ISSUE TITLE
Remove resources directory

### ISSUE THREAD

**Issue by bssb** [mattbutton/silhouette-hugo#2]
Nice theme, I really like what you've done. I just wanted to mention that the resources directory is automatically generated by hugo, so there's no need to keep it in the repository. You may want to create a .gitignore file to exclude it.

**Comment by mattbutton** [comment]
Thanks, glad you like the theme! 

I was asked to include the resources directory as part of the theme submission process here: https://github.com/gohugoio/hugoThemes/issues/517#issuecomment-447990625 . Based on this, I'm keen to keep it in the repo.

**Comment by bssb** [comment]
Oh ok I didn't know that. I'll close this then.
