### ISSUE TITLE
Newlines in introDescription

### ISSUE THREAD

**Issue by thanh-hai-tran** [mattbutton/silhouette-hugo#6]
Hi, 

Do you know how I can add newlines in the field introDescription. I have tried the following but it is not successful. Thank you very much!

`introDescription = "Hi, I'm Steve Francia. 
Author, Speaker, Developer, Creator of Hugo, Cobra and spf13-vim. 
Former Docker and MongoDB."`

Best regards,
Thanh Hai

**Comment by mattbutton** [comment]
Hi Than Hai,

Try a regular HTML line break element:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br

i.e.

```
introDescription = "Hi, I'm Steve Francia. <br/> Author, Speaker, Developer, Creator of Hugo, Cobra and spf13-vim. <br/> Former Docker and MongoDB."
```
